package com.example.super60.Model;

public enum Department {
   NEPHROLOGY,NEUROLOGY,OBSTETRICS_AND_GYNECOLOGY,ONCOLOGY,
    OPHTHALMOLOGY,ORTHOPEDICS,OTOLARYNGOLOGY,
    PEDIATRICS,PSYCHIATRY,PULMONOLOGY,RADIOLOGY,SURGERY,UROLOGY
}
